apiVersion: apps/v1 # Changed from extensions/v1beta1 to apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector: # Added selector
    matchLabels:
      app: web-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: web-deployment
    spec:
      containers:
      - name: web-depoyment
        image: mcr.microsoft.com/azuredocs/aci-helloworld
        ports:
        - containerPort: 80